before_script:
  - docker info
  - kubectl get no

deploy:
  variables:
    REGISTRY: 'gitlab.blockshine.net:4567'
    LIBRARY: 'webplatform/open-api'
  script:
    - gradle clean build -Denv=$CI_COMMIT_REF_NAME
    - docker build -t $REGISTRY/$LIBRARY:$CI_COMMIT_SHA .
    - docker push $REGISTRY/$LIBRARY:$CI_COMMIT_SHA
    - kubectl set image deployment/open-api open-api=$REGISTRY/$LIBRARY:$CI_COMMIT_SHA -n $CI_COMMIT_REF_NAME
  only:
    - test
